# Generated by Django 5.1.5 on 2025-02-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personagem",
            name="jogador",
        ),
        migrations.AlterField(
            model_name="campanha",
            name="jogadores",
            field=models.ManyToManyField(
                related_name="campanhas_jogador", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="campanha",
            name="mestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campanhas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
