# Generated by Django 5.1.5 on 2025-02-27 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_personagem_jogador_alter_campanha_jogadores_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheRespostaIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("resposta", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.campanha",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "campanha", "prompt")},
            },
        ),
    ]
