# Generated by Django 5.1.5 on 2025-03-05 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_usoia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logapi",
            name="acao",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="logapi",
            name="data_hora",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="logapi",
            name="detalhes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
