# Generated by Django 5.1.5 on 2025-03-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_logatividade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campanha",
            name="jogadores",
        ),
    ]
