# Generated by Django 5.1.5 on 2025-03-26 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0011_cachelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegraRPG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("categoria", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("fonte", models.CharField(blank=True, max_length=255, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras",
                        to="api.sistemarpg",
                    ),
                ),
            ],
        ),
    ]
