# Generated by Django 5.1.5 on 2025-04-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_cachelog"),
        ("rpg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FonteRPG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("jogador", "Livro do Jogador"),
                            ("mestre", "Guia do Mestre"),
                            ("monstros", "Livro dos Monstros"),
                            ("suplemento", "Suplemento"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fontes",
                        to="api.sistemarpg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Magia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("nivel", models.PositiveIntegerField()),
                ("escola", models.CharField(max_length=100)),
                ("tempo_conjuracao", models.CharField(max_length=100)),
                ("alcance", models.CharField(max_length=100)),
                ("componentes", models.CharField(max_length=100)),
                ("duracao", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ritual", models.BooleanField(default=False)),
                ("concentracao", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magias",
                        to="api.sistemarpg",
                    ),
                ),
            ],
        ),
    ]
