# Generated by Django 5.1.5 on 2025-04-01 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_cachelog"),
        ("rpg", "0002_fonterpg_magia"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasseRPG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("dados_vida", models.CharField(max_length=50)),
                ("proficiencias", models.TextField(blank=True, null=True)),
                ("pericias_disponiveis", models.TextField(blank=True, null=True)),
                ("habilidades_nivel", models.JSONField(blank=True, default=dict)),
                ("magias_conhecidas", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="api.sistemarpg",
                    ),
                ),
            ],
        ),
    ]
